In [1]:
# Install required libraries (if not installed)
!pip install dash plotly pandas openpyxl

# Import required libraries
import pandas as pd
import plotly.express as px
from dash import Dash, dcc, html
from dash.dependencies import Input, Output

Requirement already satisfied: dash in c:\users\jhasn\anaconda3\lib\site-packages (3.0.1)
Requirement already satisfied: plotly in c:\users\jhasn\anaconda3\lib\site-packages (5.24.1)
Requirement already satisfied: pandas in c:\users\jhasn\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: openpyxl in c:\users\jhasn\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: Flask<3.1,>=1.0.4 in c:\users\jhasn\anaconda3\lib\site-packages (from dash) (3.0.3)
Requirement already satisfied: Werkzeug<3.1 in c:\users\jhasn\anaconda3\lib\site-packages (from dash) (3.0.3)
Requirement already satisfied: importlib-metadata in c:\users\jhasn\anaconda3\lib\site-packages (from dash) (7.0.1)
Requirement already satisfied: typing-extensions>=4.1.1 in c:\users\jhasn\anaconda3\lib\site-packages (from dash) (4.11.0)
Requirement already satisfied: requests in c:\users\jhasn\anaconda3\lib\site-packages (from dash) (2.32.3)
Requirement already satisfied: retrying in c:\users\jhasn\anaconda3\lib\site-packages (from dash) (1.3.4)
Requirement already satisfied: nest-asyncio in c:\users\jhasn\anaconda3\lib\site-packages (from dash) (1.6.0)
Requirement already satisfied: setuptools in c:\users\jhasn\anaconda3\lib\site-packages (from dash) (75.1.0)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\jhasn\anaconda3\lib\site-packages (from plotly) (8.2.3)
Requirement already satisfied: packaging in c:\users\jhasn\anaconda3\lib\site-packages (from plotly) (24.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\jhasn\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jhasn\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jhasn\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jhasn\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: et-xmlfile in c:\users\jhasn\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: Jinja2>=3.1.2 in c:\users\jhasn\anaconda3\lib\site-packages (from Flask<3.1,>=1.0.4->dash) (3.1.4)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\jhasn\anaconda3\lib\site-packages (from Flask<3.1,>=1.0.4->dash) (2.2.0)
Requirement already satisfied: click>=8.1.3 in c:\users\jhasn\anaconda3\lib\site-packages (from Flask<3.1,>=1.0.4->dash) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in c:\users\jhasn\anaconda3\lib\site-packages (from Flask<3.1,>=1.0.4->dash) (1.6.2)
Requirement already satisfied: six>=1.5 in c:\users\jhasn\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\jhasn\anaconda3\lib\site-packages (from Werkzeug<3.1->dash) (2.1.3)
Requirement already satisfied: zipp>=0.5 in c:\users\jhasn\anaconda3\lib\site-packages (from importlib-metadata->dash) (3.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\jhasn\anaconda3\lib\site-packages (from requests->dash) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jhasn\anaconda3\lib\site-packages (from requests->dash) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\jhasn\anaconda3\lib\site-packages (from requests->dash) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jhasn\anaconda3\lib\site-packages (from requests->dash) (2024.8.30)
Requirement already satisfied: colorama in c:\users\jhasn\anaconda3\lib\site-packages (from click>=8.1.3->Flask<3.1,>=1.0.4->dash) (0.4.6)

In [2]:
# Load dataset (update the path as per your system)
file_path = r"C:\Users\jhasn\Downloads\DataAnalyst_Assesment_Dataset.xlsx"  # Use raw string (r"") to avoid errors
df = pd.read_excel(file_path, sheet_name="Large_Fake_Bookings_With_Discre")

# Display basic info
print(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Booking ID         1000 non-null   object
 1   Customer ID        1000 non-null   object
 2   Customer Name      1000 non-null   object
 3   Booking Type       1000 non-null   object
 4   Booking Date       1000 non-null   datetime64[ns]
 5   Status             1000 non-null   object
 6   Class Type         328 non-null    object
 7   Instructor         270 non-null    object
 8   Time Slot          795 non-null    object
 9   Duration (mins)    795 non-null    float64
 10  Price              1000 non-null   float64
 11  Facility           672 non-null    object
 12  Theme              273 non-null    object
 13  Subscription Type  0 non-null      float64
 14  Service Name       1000 non-null   object
 15  Service Type       1000 non-null   object
 16  Customer Email     906 non-null    object
 17  Customer Phone     895 non-null    object
dtypes: datetime64[ns](1), float64(3), object(14)
memory usage: 140.8+ KB
None

,Booking ID,Customer ID,Customer Name,Booking Type,Booking Date,Status,Class Type,Instructor,Time Slot,Duration (mins),Price,Facility,Theme,Subscription Type,Service Name,Service Type,Customer Email,Customer Phone
0,279d92c6-ce26-47c0-8915-e45b77fe20e2,00901ce3-3d86-4c97-bca2-40ccac2fb99f,Customer 1,Facility,2025-05-30,Pending,NaN,NaN,10:00:00,90.0,42.74,Party Room,NaN,NaN,Party Room,Facility,customer1@example.com,001-730-9034
1,415bfcbe-1a2e-4d4b-809a-4c5b606653b1,b82db986-bd52-4b07-bdd8-aa8cf2016241,Customer 2,Birthday Party,2025-05-29,Pending,NaN,NaN,NaN,NaN,182.06,Party Room,Superhero,NaN,Party Room,Birthday Party,customer2@example.com,001-537-5668
2,2100024b-46fc-47b5-ac1c-047d007a4723,6bbb6e83-9577-4f64-80b0-f073132d18f3,Customer 3,Birthday Party,2025-05-09,Confirmed,NaN,NaN,11:00:00,120.0,207.50,Play Area,NaN,NaN,Play Area,Facility,customer3@example.com,001-880-7769
3,74936def-088f-4d34-bad1-dfa76f78b704,f16f5beb-6a7d-4493-a19e-a30dbbd206e9,Customer 4,Birthday Party,2025-06-07,Pending,NaN,NaN,12:00:00,90.0,203.20,Play Area,NaN,NaN,Play Area,Birthday Party,customer4@example.com,001-491-3107
4,6272b4e7-a508-4ed7-bae0-21f7293287a8,eb297435-93d1-4e65-8dd4-6450922305cb,Customer 5,Class,2025-04-13,Pending,Art,NaN,15:00:00,120.0,161.14,NaN,NaN,NaN,Art,Class,customer5@example.com,001-718-3794

In [3]:
# Initialize Dash app
app = Dash(__name__)

In [4]:
app.layout = html.Div([
    html.H1("Booking Analytics Dashboard", style={'textAlign': 'center'}),

    # Booking trend graph
    dcc.Graph(id='booking-trend'),

    # Dropdown for filtering booking type
    dcc.Dropdown(
        id='booking-type-filter',
        options=[{'label': bt, 'value': bt} for bt in df['Booking Type'].unique()],
        placeholder="Select Booking Type",
    ),

    # Booking type breakdown graph
    dcc.Graph(id='booking-type-breakdown')
])

In [5]:
# Callback for booking trend visualization
@app.callback(
    Output('booking-trend', 'figure'),
    Input('booking-type-filter', 'value')
)
def update_trend(booking_type):
    """Updates the booking trend graph based on selected booking type"""
    temp_df = df.copy()
    if booking_type:
        temp_df = temp_df[temp_df['Booking Type'] == booking_type]
    fig = px.histogram(temp_df, x='Booking Date', title="Booking Trend Over Time")
    return fig

# Callback for revenue breakdown by service
@app.callback(
    Output('booking-type-breakdown', 'figure'),
    Input('booking-type-filter', 'value')
)
def update_breakdown(booking_type):
    """Updates the pie chart showing revenue breakdown by service"""
    temp_df = df.copy()
    if booking_type:
        temp_df = temp_df[temp_df['Booking Type'] == booking_type]
    fig = px.pie(temp_df, names='Service Name', values='Price', title="Revenue Breakdown by Service")
    return fig

In [6]:
if __name__ == "__main__":
    app.run(debug=True, use_reloader=False)  # use_reloader=False prevents the app from restarting twice